[package]
name = "solana"
version = "0.1.0"
edition = "2021"
author = ["Russell Wong"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13"
bs58 = "0.4"
log = "0.4"
serde = "1"
serde_derive = "1"
serde_json = "1"
solana-sdk = { git = "https://github.com/solana-labs/solana.git" }
web3-core = { path = "../core" }
