[package]
name = "web3-core"
version = "0.1.0"
edition = "2021"
author = ["Russell Wong"]

[dependencies]
async-trait = "0.1"
futures = "0.3"
reqwest = { version = "0.11.9", features = ["json"] }
serde = "1"
serde_derive = "1"
serde_json = "1"
thiserror = "1.0"
