use {
    super::{ShardLayout, SimpleNightshadeShardLayout, Validator},
    std::collections::HashMap,
};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GenesisConfig {
    pub avg_hidden_validator_seats_per_shard: Vec<u64>,
    pub block_producer_kickout_threshold: u64,
    pub chain_id: String,
    pub chunk_producer_kickout_threshold: u64,
    pub dynamic_resharding: bool,
    pub epoch_length: u64,
    pub fishermen_threshold: String,
    pub gas_limit: u64,
    pub gas_price_adjustment_rate: (u64, u64),
    pub genesis_height: u64,
    pub genesis_time: String,
    pub max_gas_price: String,
    pub max_inflation_rate: (u64, u64),
    pub min_gas_price: String,
    pub minimum_stake_divisor: u64,
    pub minimum_stake_ratio: (u64, u64),
    pub num_block_producer_seats: u64,
    pub num_block_producer_seats_per_shard: Vec<u64>,
    pub num_blocks_per_year: u64,
    pub online_max_threshold: (u64, u64),
    pub online_min_threshold: (u64, u64),
    pub protocol_reward_rate: (u64, u64),
    pub protocol_treasury_account: String,
    pub protocol_upgrade_num_epochs: u64,
    pub protocol_upgrade_stake_threshold: (u64, u64),
    pub protocol_version: u64,
    pub shard_layout: HashMap<String, ShardLayout>,
    pub simple_nightshade_shard_layout: HashMap<String, SimpleNightshadeShardLayout>,
    pub total_supply: String,
    pub transaction_validity_period: u64,
    pub validators: Vec<Validator>,
}
