#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LimitConfig {
    pub initial_memory_pages: u64,
    pub max_actions_per_receipt: u64,
    pub max_arguments_length: u64,
    pub max_contract_size: u64,
    pub max_functions_number_per_contract: u64,
    pub max_gas_burnt: u64,
    pub max_length_method_name: u64,
    pub max_length_returned_data: u64,
    pub max_length_storage_key: u64,
    pub max_length_storage_value: u64,
    pub max_memory_pages: u64,
    pub max_number_bytes_method_names: u64,
    pub max_number_input_data_dependencies: u64,
    pub max_number_logs: u64,
    pub max_number_registers: u64,
    pub max_promises_per_function_call_action: u64,
    pub max_register_size: u64,
    pub max_stack_height: u64,
    pub max_total_log_length: u64,
    pub max_total_prepaid_gas: u64,
    pub max_transaction_size: u64,
    pub registers_memory_limit: u64,
    pub stack_limiter_version: u64,
}
